# Functions

# lambda expressions

Used when the function is only used once 

In [1]:
def times2(var):
    return var*2

In [2]:
times2(2)

4

In [3]:
lambda var: var*2

<function __main__.<lambda>(var)>

# map & filter

any function applied using map applies the function to the whole list.

In [4]:
seq = [1,2,3,4,5]

In [5]:
map(times2,seq)

In [6]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [7]:
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

Only returns the values which satisfy the function

In [8]:
filter(lambda item: item%2 == 0,seq)

In [9]:
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

# Numpy

In [12]:
import numpy as np

List

In [10]:
my_list = [1,2,3]
my_list

[1, 2, 3]

An array can be created directly by converting a list or a list of lists

In [14]:
arr=np.array(my_list)

In [15]:
type(arr)

numpy.ndarray

In [17]:
type(my_list)

list

In [ ]:
array=[1,2,3,4]
color=['red','blue']

In [18]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# built-in methods

# arange

Returns evenly spaced values in a given interval

In [20]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [22]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


# zeros and ones

Generate an array of zeros and ones.

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# eye
Creates an identity matrix

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)

In [27]:
np.random.rand(2)

array([0.2776384 , 0.68672196])

In [28]:
np.random.rand(5,5)

array([[0.70920779, 0.18284164, 0.04836732, 0.22526306, 0.59995663],
       [0.96599298, 0.86287721, 0.36107092, 0.85202762, 0.00950492],
       [0.41473519, 0.50324007, 0.99074594, 0.70631098, 0.51805278],
       [0.04044948, 0.35137767, 0.48339995, 0.34260325, 0.29783058],
       [0.39867406, 0.46855837, 0.93302775, 0.05725542, 0.78780749]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [29]:
np.random.randint(1,100)

98

In [30]:
np.random.randint(1,100,10)

array([84, 18, 26, 52, 53, 92, 63, 94, 24, 43])

## Reshape
Returns an array containing the same data with a new shape.

In [52]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [48]:
L=[ 25,  1,  2,  3,  4,  5,  6,  7,  8,  -1, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24]
arr=np.array(L)

In [44]:
arr

array([25,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape
Returns an array containing the same data with a new shape.

In [4]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Max value of array

In [41]:
arr.max()

24

Index of max value of array

In [45]:
arr.argmax()

0

Min value of array

In [46]:
arr.min()

1

Index of min value of array

In [49]:
arr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method):

In [50]:
arr.shape

(25,)

In [51]:
arr.reshape(1,25).shape

(1, 25)

# accessing arrays
numpy arrays are accessed in the same way lists are accessed.

In [63]:
arr=np.arange(0,25)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
arr[-1]

24

In [66]:
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr[-5:-1]

array([20, 21, 22, 23])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [70]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Matrix[row][col]

In [71]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [72]:
# Getting individual element value
arr_2d[1][0]

20

In [73]:
# Getting individual element value
arr_2d[1,0]

20

In [75]:
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Arithmetic
You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [89]:
arr = np.arange(0,10)


In [87]:
arr

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [77]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [86]:
arr=arr * arr* arr

In [83]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [92]:
l=[1,4,25,9,81,64]
arr=np.array(l)
arr

array([ 1,  4, 25,  9, 81, 64])

In [93]:
np.sqrt(arr)

array([1., 2., 5., 3., 9., 8.])

In [94]:
np.max(arr) 

81

In [ ]:
np.log(arr)

In [96]:
np.log()

4

# Pandas

In [97]:
import pandas as pd

## series

A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

### Creating a Series

You can convert a list,numpy array, or dictionary to a Series:

In [103]:
labels = ['hi','hello','cd']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [100]:
df=pd.read_csv("USA_Housing-Copy1.csv")

In [99]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [105]:
pd.Series(index=labels,data=my_list)

hi       10
hello    20
cd       30
dtype: int64

In [108]:
pd.Series(my_list,labels)

hi       10
hello    20
cd       30
dtype: int64

In [109]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [110]:
pd.Series(arr,labels)

hi       10
hello    20
cd       30
dtype: int32

## Using an Index

The key to using a Series is understanding its index. 

In [118]:
ser1 = pd.Series(index=[1,2,3,4],data= ['USA', 'Germany','USSR', 'Japan'])                                   

In [119]:
ser1

1        USA
2    Germany
3       USSR
4      Japan
dtype: object

In [113]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])                                   

In [114]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [122]:
ser2[0]

1

In [121]:
ser1[1]

'USA'

## dataframes

Loading dataframe

In [123]:
df=pd.read_csv("USA_Housing-Copy1.csv")

In [129]:
df.tail()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
4995      60567.944140             7.830362                   6.137356   
4996      78491.275435             6.999135                   6.576763   
4997      63390.686886             7.250591                   4.805081   
4998      68001.331235             5.534388                   7.130144   
4999      65510.581804             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population         Price  \
4995                          3.46     22837.361035  1.060194e+06   
4996                          4.02     25616.115489  1.482618e+06   
4997                          2.13     33266.145490  1.030730e+06   
4998                          5.44     42625.620156  1.198657e+06   
4999                          4.07     46501.283803  1.298950e+06   

                                                Address  
4995                   USNS Williams\nFPO AP 30153-7653  
4996              PSC 9258, Box 8489\nAPO AA 42991-3352  
4997  4215 Tracy Garden Suite 076\nJoshualand, VA 01...  
4998                          USS Wallace\nFPO AE 73316  
4999  37778 George Ridges Apt. 509\nEast Holly, NV 2...

In [130]:
from numpy.random import randn

In [171]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [172]:
df.head()

W         X         Y         Z
A -1.178520  0.635621 -2.305978  2.842865
B  0.356540  0.685772  0.753230  0.763323
C  0.601854 -0.239218  0.117648  1.429923
D -0.939970  2.234953 -0.455850 -0.548952
E -1.505876  0.410429  1.939043 -0.496407

In [133]:
df.tail(1)

W         X         Y         Z
E -1.684225 -1.053574  1.633153  0.986721

Selcting and indexing 

In [135]:
df['W']

A    1.252928
B   -2.000160
C    0.237974
D    0.541435
E   -1.684225
Name: W, dtype: float64

In [136]:
df[['Y','Z']]

Y         Z
A  1.017808 -1.537983
B -2.189602  2.014519
C  0.139328  0.614338
D -1.276379  0.840052
E  1.633153  0.986721

In [139]:
type(df[['W','Y']])

pandas.core.frame.DataFrame

Creating a new column

In [140]:
df[['W','Y']]

W         Y
A  1.252928  1.017808
B -2.000160 -2.189602
C  0.237974  0.139328
D  0.541435 -1.276379
E -1.684225  1.633153

In [150]:
df['new'] = df['W'] + df['Y']

In [153]:
df.head()

W         X         Y         Z
A  1.252928  1.950693  1.017808 -1.537983
B -2.000160  1.249491 -2.189602  2.014519
C  0.237974  0.314628  0.139328  0.614338
D  0.541435 -0.277571 -1.276379  0.840052
E -1.684225 -1.053574  1.633153  0.986721

Removing Columns

In [152]:
df=df.drop(labels='new',axis=1)

In [148]:
df.drop('new',axis=1,inplace=True)

Conditional Selection

In [156]:
df

W         X         Y         Z
A  1.252928  1.950693  1.017808 -1.537983
B -2.000160  1.249491 -2.189602  2.014519
C  0.237974  0.314628  0.139328  0.614338
D  0.541435 -0.277571 -1.276379  0.840052
E -1.684225 -1.053574  1.633153  0.986721

In [157]:
df>0

W      X      Y      Z
A   True   True   True  False
B  False   True  False   True
C   True   True   True   True
D   True  False  False   True
E  False  False   True   True

In [158]:
df[df>0]

W         X         Y         Z
A  1.252928  1.950693  1.017808       NaN
B       NaN  1.249491       NaN  2.014519
C  0.237974  0.314628  0.139328  0.614338
D  0.541435       NaN       NaN  0.840052
E       NaN       NaN  1.633153  0.986721

In [159]:
df

W         X         Y         Z
A  1.252928  1.950693  1.017808 -1.537983
B -2.000160  1.249491 -2.189602  2.014519
C  0.237974  0.314628  0.139328  0.614338
D  0.541435 -0.277571 -1.276379  0.840052
E -1.684225 -1.053574  1.633153  0.986721

In [160]:
df[df['W']>0]

W         X         Y         Z
A  1.252928  1.950693  1.017808 -1.537983
C  0.237974  0.314628  0.139328  0.614338
D  0.541435 -0.277571 -1.276379  0.840052

In [161]:
df[df['W']>0]['Y']

A    1.017808
C    0.139328
D   -1.276379
Name: Y, dtype: float64

In [162]:
df[df['W']>0][['Y','X']]

Y         X
A  1.017808  1.950693
C  0.139328  0.314628
D -1.276379 -0.277571

In [163]:
df.head()

W         X         Y         Z
A  1.252928  1.950693  1.017808 -1.537983
B -2.000160  1.249491 -2.189602  2.014519
C  0.237974  0.314628  0.139328  0.614338
D  0.541435 -0.277571 -1.276379  0.840052
E -1.684225 -1.053574  1.633153  0.986721

In [164]:
df[(df['W']>0) & (df['Y'] > 1)]

W         X         Y         Z
A  1.252928  1.950693  1.017808 -1.537983

## Multilevel Index

In [165]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [166]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1  0.494727 -0.515338
   2  0.140610  0.875735
   3  1.094534  0.825981
G2 1 -1.747361  0.676124
   2 -0.362378  1.433662
   3  1.753741  0.393424

In [170]:
df.loc['G1']

A         B
1  0.494727 -0.515338
2  0.140610  0.875735
3  1.094534  0.825981

In [ ]:
df.loc['G1'].loc[1]

## Real world applications

In [192]:
df=pd.read_csv("USA_Housing-Copy1.csv")

In [193]:
df.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [196]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object 
dtypes: float64(6), object(1)
memory usage: 273.6+ KB


The rows are considered as data objects and the columns are the different features and attributes

## Missing Data
How to deal with missing values

In [188]:
import numpy as np

In [197]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [190]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [191]:
df.isnull()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

Drop the rows which have null values

In [198]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [199]:
df.dropna(axis=1) # columns 

C
0  1
1  2
2  3

In [207]:
df.head()

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [208]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [210]:
df[['A','C']].dropna()

A  C
0  1.0  1
1  2.0  2

In [205]:
df[['A','C']].dropna() # minimum number of null values it needs to drop a row

A  C
0  1.0  1
1  2.0  2

filling the null values

In [215]:
df.head()

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [214]:
df.fillna(value=0)

A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [221]:
A_mean=df['A'].mean()
df['A'].fillna(value=A_mean)

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [222]:
df['B'].fillna(value=df['B'].mean())

0    5.0
1    5.0
2    5.0
Name: B, dtype: float64

## Group by

groupby() is used to group rows together based off of a column name.

In [223]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)

In [227]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

groupby always creates a object so it needs to be combined with aggregate methods

In [225]:
df.groupby('Company')

In [233]:
df[['Company','Sales']].groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [229]:
by_comp = df.groupby("Company")

other aggregate methods

In [234]:
by_comp.min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [235]:
by_comp.count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [236]:
by_comp.describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [237]:
by_comp.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

## Merging Joining and Concatenating

In [238]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [239]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [240]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [241]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

### Concatenation
Concatenation basically glues together DataFrames. Keep in mind that dimensions should match along the axis you are concatenating on. You can use **pd.concat** and pass in a list of DataFrames to concatenate together:

In [242]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [243]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [244]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

### merge
The **merge** function allows you to merge DataFrames together using a similar logic as merging SQL Tables together.

In [245]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [246]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [247]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

### joining
Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame.

In [248]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [250]:
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [249]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [251]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [252]:
left.join(right, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

## Operations

In [264]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

returns the unique values of the column

In [254]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

returns the number of unique values

In [255]:
df['col2'].nunique()

3

returns the count of each value

In [256]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

### applying functions

In [267]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [258]:
def times2(x):
    return x*2

In [266]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [268]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [269]:
df['col1'].sum()

10

Dropping a column permanently

In [270]:
del df['col1']

In [271]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

can also be done by setting axis to 1 

In [ ]:
df.drop('col1',axis=1)

Sorting values 

In [272]:
df.sort_values(by='col2')

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

### Reading and saving files

In [ ]:
df = pd.read_csv('USA_Housing-Copy1.csv')
df

saving

In [ ]:
df.to_csv('example',index=False)